apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged-2
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: host-data-volume
      hostPath:
        path: /var/lib/my-app-data 
        type: DirectoryOrCreate
