apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged-3
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 0 # 0 is the UID for the root user
