apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DisallowRunRoot
metadata:
  name: disallowrunroot
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - audit-zone