apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    verbs: ["create", "update", "patch"]
    resources:
      - group: ""
        resources: ["pods"]
  - level: Metadata
    resources:
      - group: "*"
        resources: ["*"]

  - level: Metadata
    verbs: [ "create" ]
    resources:
      - group: ""
        resources: [ "pods" ]
    namespaceSelector:
      matchLabels:
        pod-security.kubernetes.io/enforce: "restricted"