apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    verbs: []
    resources:
      - group: ""
        resources:
          [
            "pods",
            "secrets",
            "configmaps",
            "serviceaccounts",
            "roles",
            "rolebindings",
          ]
  - level: Metadata
    resources:
      - group: ""
        resources: ["*"]
